# Generated by Django 3.0.4 on 2020-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0008_auto_20200625_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='experience',
            field=models.IntegerField(default=2),
        ),
    ]
