# Generated by Django 3.0.4 on 2020-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0009_lawyer_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='services',
            field=models.ManyToManyField(to='law.Service'),
        ),
    ]
