# Generated by Django 3.0.4 on 2020-07-01 08:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0013_auto_20200629_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_Name', models.CharField(max_length=50)),
                ('Appointment_Phone_Number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')])),
                ('Appointment_Email', models.EmailField(max_length=254)),
                ('Appointment_Service', models.CharField(max_length=50)),
                ('Appointment_DateAndTime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law.Client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law.Lawyer')),
            ],
        ),
    ]
