# Generated by Django 3.0.4 on 2020-07-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0014_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lawyer',
        ),
    ]
