# Generated by Django 3.0.4 on 2020-07-01 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0015_auto_20200701_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_DateAndTime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_Email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_Phone_Number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_Service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_Name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='law.Client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='law.Service'),
        ),
        migrations.AddField(
            model_name='client',
            name='Phone_Number',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
