# Generated by Django 3.0.4 on 2020-07-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0017_appointment_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='lawyer',
        ),
    ]
