# Generated by Django 3.0.4 on 2020-07-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0018_remove_appointment_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='law.Lawyer'),
        ),
    ]
