# Generated by Django 3.0.4 on 2020-07-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0019_appointment_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='lawyer',
        ),
    ]
